version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps: 
      - checkout
      - run: sudo pip install awscli --upgrade
      - run: |
          mkdir ~/.aws
          touch ~/.aws/config
          chmod 600 ~/.aws/config
          echo "[profile eb-cli]" > ~/.aws/config
          echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
          echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - setup_remote_docker
      - run: eval $(aws ecr get-login --region $EB_REGION --no-include-email)      
      - run: docker build -t $CI_REGISTRY/$CI_REGISTRY_ID:dev -f Dockerfile.stg .
      - run: docker push $CI_REGISTRY/$CI_REGISTRY_ID:dev

  build-master:
    docker:
      - image: circleci/python:latest
    steps: 
      - checkout
      - run: sudo pip install awscli --upgrade
      - run: |
          mkdir ~/.aws
          touch ~/.aws/config
          chmod 600 ~/.aws/config
          echo "[profile eb-cli]" > ~/.aws/config
          echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
          echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - setup_remote_docker
      - run:
          name: "What was my EB_REGION environment variable?"
          command: echo ${EB_REGION}
      - run: eval $(aws ecr get-login --region $EB_REGION --no-include-email)      
      - run: docker build -t tutorial-aws-symfony-ci:latest .
      - run: docker push 254002134964.dkr.ecr.eu-west-1.amazonaws.com/tutorial-aws-symfony-ci:latest

  deploy-stg:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run: sudo pip install awsebcli --upgrade
      - run: |
          mkdir ~/.aws
          touch ~/.aws/config
          chmod 600 ~/.aws/config
          echo "[profile eb-cli]" > ~/.aws/config
          echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
          echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run: eb init --region $EB_REGION --platform Docker EB_APP
      - run: cp Dockerrun.aws.stg.json Dockerrun.aws.json
      - run: eb use EB_ENV_STG --region $EB_REGION
      - run: eb deploy -v --staged --profile eb-cli

  deploy-prod:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run: sudo pip install awsebcli --upgrade
      - run: |
          mkdir ~/.aws
          touch ~/.aws/config
          chmod 600 ~/.aws/config
          echo "[profile eb-cli]" > ~/.aws/config
          echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
          echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run: eb init --region $EB_REGION --platform Docker EB_APP
      - run: cp Dockerrun.aws.prod.json Dockerrun.aws.json
      - run: eb use EB_ENV_STG --region $EB_REGION
      - run: eb deploy -v --staged --profile eb-cli

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - deploy-stg:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master

  build-deploy:
    jobs:
      - build-master:
          filters:
            branches:
              only:
                - master
      - deploy-prod:
          requires:
            - build-master
          filters:
            branches:
              only:
                - master