version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run: sudo pip install awscli --upgrade
      - run: |
          mkdir ~/.aws
          touch ~/.aws/config
          chmod 600 ~/.aws/config
          echo "[profile eb-cli]" > ~/.aws/config
          echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
          echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - setup_remote_docker
      - run: eval $(aws ecr get-login --region eu-central-1 --no-include-email)
      - run: docker build -t $CI_REGISTRY/$CI_REGISTRY_ID:dev -f Dockerfile.stg .
      - run: docker push $CI_REGISTRY/$CI_REGISTRY_ID:dev

  build-master:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run: sudo pip install awscli --upgrade
      - run: |
          mkdir ~/.aws
          touch ~/.aws/config
          chmod 600 ~/.aws/config
          echo "[profile eb-cli]" > ~/.aws/config
          echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
          echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run: docker build -t $CI_REGISTRY/$CI_REGISTRY_ID:latest .
      - run: docker push $CI_REGISTRY/$CI_REGISTRY_ID:latest

  deploy-stg:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run: sudo pip install awsebcli --upgrade
      - run: |
          mkdir ~/.aws
          touch ~/.aws/config
          chmod 600 ~/.aws/config
          echo "[profile eb-cli]" > ~/.aws/config
          echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
          echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run: eb init --region eu-central-1 --platform Docker tutorial-aws-symfony-ci
      - run: cp Dockerrun.aws.stg.json Dockerrun.aws.json
      - run: eb use tutorial-aws-symfony-ci-stg --region eu-central-1
      - run: eb deploy -v --staged --profile eb-cli

  deploy-prod:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run: sudo pip install awsebcli --upgrade
      - run: |
          mkdir ~/.aws
          touch ~/.aws/config
          chmod 600 ~/.aws/config
          echo "[profile eb-cli]" > ~/.aws/config
          echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
          echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run: eb init --region eu-central-1 --platform Docker tutorial-aws-symfony-ci
      - run: cp Dockerrun.aws.prod.json Dockerrun.aws.json
      - run: eb use tutorial-aws-symfony-ci-prod --region eu-central-1
      - run: eb deploy -v --staged --profile eb-cli

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - deploy-stg:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master

  build-deploy:
    jobs:
      - build-master:
          filters:
            branches:
              only:
                - master
      - deploy-prod:
          requires:
            - build-master
          filters:
            branches:
              only:
                - master